development:
  adapter: mysql2
  encoding: utf8
  database: waddle
  username: 'lindaweng'
  host: <%=ENV['IP']%>
  password: <%=ENV['mypassword']%>

# require 'active_record'

# ActiveRecord::Base.establish_connection({
#   adapter:  'mysql2',
#   host: 'IP 3306',
#   username: 'lindaweng',
#   password: 'mypassword',
#   database: 'waddle'
# })